### ISSUE TITLE
Mouse-over component label is not visible - CHANGE COLOR

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#106]
The color has to be changed because the light GRAY we had chosen is REALLY NOT VISIBLE.

I have done a few tests (see attachment) and I think GREEN #100F900 is the best as it is visible in all three locations (white, black and grey backgrounds) and at the same time it signals ALL CLEAR and not THIS IS A PROBLEM (as the red does).

But I am open to other suggestions.

![image](https://user-images.githubusercontent.com/4050585/98582146-87911780-2290-11eb-81e5-090e07ed78f8.png)

**Comment by Akramhar** [comment]
should be done in 0.31
