### ISSUE TITLE
Mouse-over label CHANGE SIZE

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#107]
The size of the MOUSE-OVER test in the Microscope Canvas is too small.
I am not sure what size it is now.
But it should be increased at least 1.5 fold.
In the attached image the test labels I have used are 16pt and they are OK.

![image](https://user-images.githubusercontent.com/4050585/98582466-025a3280-2291-11eb-8a67-d10b30961678.png)

**Comment by Akramhar** [comment]
this should be fixed in 0.31
