### ISSUE TITLE
Fatal error Change Validation Tier

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#117]
Opened from scratch and changed validation tier from 3 to 1.
The application went blank.
Had to restart
See attached console error messages

The same happened when opened at Tier 1 and selected Tier 1 under Validate @Tier selector
The same happened when opened at Tier 2 and selected Tier 1 under Validate @Tier selector

**Comment by strambc** [comment]
[
<img width="593" alt="Issue 117_Error 1" src="https://user-images.githubusercontent.com/4050585/102377351-8ab7ab80-3f92-11eb-9ddb-3d3f698dbb3a.png">
<img width="593" alt="Issue 117_Error 2" src="https://user-images.githubusercontent.com/4050585/102377352-8b504200-3f92-11eb-9de3-7fd329c6aaa6.png">
<img width="593" alt="Issue 117_Error 3" src="https://user-images.githubusercontent.com/4050585/102377356-8c816f00-3f92-11eb-9ed1-e0639710a54f.png">
<img width="593" alt="Issue 117_Error 4" src="https://user-images.githubusercontent.com/4050585/102377357-8d1a0580-3f92-11eb-8997-84f498fa595e.png">



](url)

**Comment by Akramhar** [comment]
this should be solved in 0.31

**Comment by strambc** [comment]
Fixed
