### ISSUE TITLE
LightSource --> IlluminationWavelengthRange button is not working

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#138]
The writing "IlluminationWavelengthRange" spills over the "+" button and does not allow to press it.
![image](https://user-images.githubusercontent.com/4050585/102522027-adfe5b80-4063-11eb-840c-c918f21acb4c.png)

**Comment by Akramhar** [comment]
should be solved in 0.31

**Comment by strambc** [comment]
Fixed
