### ISSUE TITLE
OpticalAssembly: cannot add any of the Referenced items

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#144]
Condenser:

- cannot reference existing multiple CondenserLens
- cannot reference existing multiple OpticalAperture

**Comment by strambc** [comment]
Same happens with MicroscopeTube and BeamExpander and BeamCollimator

**Comment by Akramhar** [comment]
In theOpticalAssembly:
The problem with Aperture is that they are called Aperture in the model but they are trying to get referenced as OpticalAperture.
The problem MirroringDevice is that they are called MirroringDevice in the model but they are trying to get referenced as MirrorringDevice :(

**Comment by Akramhar** [comment]
Once they are aligned, the new system in place seems to be working properly so we should be able to reference by category name and not just by element model name

**Comment by strambc** [comment]
Not sure I understand. Should I change the model? I thought we were using the category... I am confused

Caterina Strambio De Castillia, Ph.D. | CZI Imaging Scientist | Assistant Professor, Program in Molecular Medicine | University of Massachusetts Medical School |
——————————————
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On Dec 24, 2020, at 06:11, Akramhar <notifications@github.com> wrote:

﻿

Once they are aligned, the new system in place seems to be working properly so we should be able to reference by category name and not just by element model name

**Comment by strambc** [comment]
Committed change to model

Caterina Strambio De Castillia, Ph.D. | CZI Imaging Scientist | Assistant Professor, Program in Molecular Medicine | University of Massachusetts Medical School |
——————————————
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On Dec 24, 2020, at 06:52, Strambio, Caterina <Caterina.Strambio@umassmed.edu> wrote:

﻿ Not sure I understand. Should I change the model? I thought we were using the category... I am confused

Caterina Strambio De Castillia, Ph.D. | CZI Imaging Scientist | Assistant Professor, Program in Molecular Medicine | University of Massachusetts Medical School |
——————————————
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On Dec 24, 2020, at 06:11, Akramhar <notifications@github.com> wrote:

﻿

Once they are aligned, the new system in place seems to be working properly so we should be able to reference by category name and not just by element model name

**Comment by strambc** [comment]
THIS IS FIXED
