### ISSUE TITLE
Failed to Confirm Edit Microscope when TESM was loaded from Repository

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#148]
Loaded TESM from repository.
Attempted to Edit Microscope.
The initial request for Confirm seemed odd.
Edited fields.
Upon confirm the entire screen went blank.

Take the look at the attached VIDEO for a description of the issue.
https://www.dropbox.com/s/4z1zoq8ihv526p8/Issue%20148_Screen%20cast.mov?dl=0 

Error messages:
![image](https://user-images.githubusercontent.com/4050585/103163737-11109080-47d0-11eb-9f77-7e4be578422f.png)

**Comment by Akramhar** [comment]
should be solved in 0.32
