### ISSUE TITLE
Load TESM from Repository --> Component with changed name are missing

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#149]
When loaded TESM from Repository the following items are missing:

- AutoFocus --> FocusStabilizationDevice
- Direct --> FreeBeam
- FilterSet --> FilterCube
- Optovar --> MagnificationChangerLens
- SampleHolder --> StageInsert
- ObjectiveTurretFocus --> TurretObjectiveFocusing
- PiezoElectricObjectiveFocus --> IndividualObjectiveFocusing

**Comment by Akramhar** [comment]
should be solved in 0.32
