### ISSUE TITLE
Buggy positioning of elements when they are dragged and dopped

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#16]
Graphical elements are difficult to position on the canvas.
They switch their position from where they are dropped.
ALso resizing the window affects positioning.
Positioning algorithm has to be reviewed and fixed.

**Comment by Akramhar** [comment]
Connected to #33

**Comment by Akramhar** [comment]
this should not be relevant anymore
