### ISSUE TITLE
When Loading from Repo, Manufacturer list does not include new Microscopes

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#162]
Load old TESM
Update Edit Microscope fields
Save
Load from Repo, Microscope is listed under Other (Manufacturer)
Probably linked to #154 and #155

**Comment by Akramhar** [comment]
should be solved in 0.33.1

**Comment by Akramhar** [comment]
all the old microscope should end up in others now
