### ISSUE TITLE
Disappearing Images after pressing enter at the last entered value

### ISSUE THREAD

**Issue by mathomH** [WU-BIMAC/4DNMicroscopyMetadataToolReact#18]
I found that back at tier 1, examples:
1st "Edit microscope" filled Generic then "ManufactorerSpec" and hit enter -> white screen
(notice the last tab has no typing entering there = "ManufactorerSpec" is the last thing where there is anything to type)
2nd added an objective filled all information and pressed enter after the last entry -> white screen

I can not attach the saved microscopes to let you inspect the errors, so I gonna email them

**Comment by Akramhar** [comment]
Thanks Mathias, I received your email with the jsons.
Will test tomorrow and try to fix it

**Comment by Akramhar** [comment]
Problem couldnt be reproduced in version 0.0.5, more investigation is required

**Comment by Akramhar** [comment]
this is probably not relevant anymore, I'll close it and if the problem reappears we are going to reopen it
