### ISSUE TITLE
FOR SHANNON --> GUILBERT #1_config conflict between Filter cube turret and Em filter

### ISSUE THREAD

**Issue by ThomasGuilbert** [WU-BIMAC/4DNMicroscopyMetadataToolReact#182]
Hi,
Just an issue I got, on inverted stand, when filter cubes are asset with filters, once the Filter cube turret is in position too, I find no way to edit emission filters anymore. 
Whatever the zoom, the mouse position keep proposing to edit the Filter cube turret.
++

**Comment by strambc** [comment]
I was able to reproduce this issue.
The FilterCubeTurrett icon has to be modified to allow access to Em-Filter

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/109069924-df2c8500-76bf-11eb-8906-48dd3c4d0551.png)

**Comment by Akramhar** [comment]
should be done in 0.35

**Comment by strambc** [comment]
THis is not FIXED. The position of the SLOT is moved down but the snap in place remains at the same place as before
