### ISSUE TITLE
LightGuide: WavelenghtRange subelement is missing

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#19]
The element has the ChildElement Catergory but it is not present in the GUI as a subelement.

**Comment by Akramhar** [comment]
LightGuide has tier 4 while WavelenghtRange has tier 5, if you are in tier 4 you may end up not seeing the subelement. Was that the case?

**Comment by Akramhar** [comment]
There is actually a issue with component number, since its min 0 max 1.
Needs to be double checked.

**Comment by Akramhar** [comment]
Issue seems to be fixed in 0.0.6

**Comment by strambc** [comment]
This issue might be connected to #
