### ISSUE TITLE
Manage Settings --> Tool tips text add and update

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#193]
The tooltips for the following buttons have to be updated:

Edit Settings --> "Edit Image Acquisition Settings: click this button to enter general information about the acquisition settings utilized for this image"

Validate @tier:X --> "Validation Tier selector: Choose the Tier level you want to use to validate this Settings file. etc."

Save settings --> "Choose whether you want to save this Settings file to the active Micro-Meta App repository or if you want to export it to your local file system."

**Comment by strambc** [comment]
The tooltips for the following buttons have to be added:

**Comment by Akramhar** [comment]
should be done in 0.36

**Comment by strambc** [comment]
The tool tips the bottom row of buttons are not up to date.

**Comment by Akramhar** [comment]
should be done in 0.37
