### ISSUE TITLE
Plane cannot be Confirmed

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#197]
After creating 10 Planes, attempted to edit Plane 0 and Confirm did not allow to exit

![image](https://user-images.githubusercontent.com/4050585/109040263-b85c5780-769b-11eb-92ae-18fc11a51a8f.png)

**Comment by strambc** [comment]
The same happens when attempting to edit all Planes

**Comment by Akramhar** [comment]
should be fixed in 0.35
