### ISSUE TITLE
Focusing elements sizes and bounding boxes issues

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#20]
In case of elements associated with an oblong image (stages, optovar etc.) sizes are still an issue +
bounding boxes are often way too large

Was this issue already dealt with?

**Comment by Akramhar** [comment]
no, it's still an issue.
 it's something we can take down the line in my opinion together with the resizing and moving issue.
the whole app need a way better way of dealing with images / size of components / components moving when resizing the window

**Comment by Akramhar** [comment]
this should not be relevant anymore
