### ISSUE TITLE
Manage Settings: Update GUI for all Edit XYX Settings

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#220]
Update GUI for all Edit XYZ Settings in main Manage Settings window to allow selection of component and subsequent editing of Settings referring to the selected component.
This applies to:
ObjectiveSettings
MicroscopeTableSettings
SamplePositioningSettings
ImagingEnvironment

MicroscopeStandSettings will be similar but will not allow to select a component as there is only one MicroscopeStand per Instrument at the moment

**Comment by strambc** [comment]
Related and supersedes #201

**Comment by Akramhar** [comment]
should be in 0.36
