### ISSUE TITLE
Manage Settings: Change descriptions for Add multiple Planes interface

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#222]
1. General --> "This interface allows you to add multiple image Planes to this Image. For example, in case the Image has 10 Z-sections, 3 channels, and 1 time-points, the interface should be used to add three batches (one per Channel) of 10 Planes each."
2. NumberOfPlanes --> "Insert the number of Planes to be inserted as part of this batch".
3. Z-Increment --> "Select this if you want the different Planes in this batch to have increasing Z-dimension numbers."
4. T-Increment --> "Select this if you want the different Planes in this batch to have increasing timepoint-dimension numbers."
5. C-Increment --> "Select this if you want the different Planes in this batch to have increasing channel-dimension numbers."
6. TimeStamp-Increment -->  "Insert the TimeStamp increment to be set between image Planes in this batch."

**Comment by Akramhar** [comment]
should be fixed in 0.35

**Comment by strambc** [comment]
This is related to #253
