### ISSUE TITLE
Camera/WavelengthRange/Wavelength: field registers as empty when value has been added

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#226]
![image](https://user-images.githubusercontent.com/4050585/109201099-6ab11f00-776f-11eb-8f14-34923f925a7d.png)

**Comment by strambc** [comment]
TESM microscope 
[STRAMBIO_tesm_022421.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/6045109/STRAMBIO_tesm_022421.txt)

**Comment by strambc** [comment]
Also, the arrows to increase or decrease the number do not work in that field and in all other fields

**Comment by strambc** [comment]
the Arrows problem disappeared when app was relaunched

**Comment by Akramhar** [comment]
there is an error in that file:
![image](https://user-images.githubusercontent.com/3996749/110382711-4ab01400-8029-11eb-9401-fe9266f07711.png)
