### ISSUE TITLE
FATAL ERROR: Manage Settings --> When confirming LightSourceSettings jumps to Edit Channel and crashes

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#230]
This issue was already noted and appears unchanged.
When clicking on LightSource to edit settings and confirming, the interface jumps to Channel and then when attempting to confirm Channel the application gives a FATAL ERROR

**Comment by Akramhar** [comment]
should be done in 0.36
