### ISSUE TITLE
MANAGE SETTINGS --> Channel GUI Excitatin, Emission and Dichroic element choices lack transmissin ranges

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#234]
Only the first Excitation, Emission, and Dichroic elements contain Transmission Ranges.
All others do not show it.

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/109716522-fc0b0180-7b72-11eb-9ef1-0b405095755d.png)

**Comment by Akramhar** [comment]
should be solved in 0,36
