### ISSUE TITLE
FOR SHANNON --> FLUORESCENCE is written wrongly in the light source ICON LABEL 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#235]
![image](https://user-images.githubusercontent.com/4050585/110392945-bf8a4a80-8037-11eb-9322-dd17f0ac7c0d.png)

The labels should be FLUORESCENCE.
Instead, it says FLOURESCENCE

**Comment by Akramhar** [comment]
should be in 0.36
