### ISSUE TITLE
ALERT MODEL CHANGE --> Changed  IlluminationWavelengthRange requirement level

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#236]
The IlluminationWavelenghtRange optional level was changed to 0 to unbound (was 1 to unbound).

**Comment by Akramhar** [comment]
should be in 0.36

**Comment by strambc** [comment]
This was not fixed!
The IlluminationWavelengthRange remains 1-unbounded

**Comment by Akramhar** [comment]
should be done in 0.37
