### ISSUE TITLE
ALERT MODEL CHANGE --> LightSourceCoupling/LightGuide/WavelengthRange cardinality change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#239]
The cardinality of LightSourceCoupling/LightGuide/WavelengthRange was changed from 1-unbound to 0 to unbound

**Comment by Akramhar** [comment]
should be in 0.36

**Comment by strambc** [comment]
This was not changed.
Cardinality remains 1 to unbounded

**Comment by Akramhar** [comment]
should be done in 0.37
