### ISSUE TITLE
Data types: are they implemented?

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#24]
There does not seem to be a restriction of what type of data can be entered in a field (i.e. string vs. float etc.)

**Comment by Akramhar** [comment]
They should be implemented, obviously a string can contain anything.
But numbers should be restricted to numeric value only for example.
We can verify that together if it's still the case

**Comment by strambc** [comment]
Does not seem to be working: when the item should be a float I can enter a string...

**Comment by Akramhar** [comment]
This needs to be addresed

**Comment by Akramhar** [comment]
should be done in 0.0.7/0.0.8 , needs to be tested
