### ISSUE TITLE
FOR SHANNON --> Upright remaining issues

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#242]
- [ ] -- Condenser elements snap slightly lower than the correct position
- [x] -- TurretObjectiveFocusing snaps lower than the correct position
- [x] -- IndividualObjectiveFocusing snaps to the original position
- [x] -- PhaseRing icons have a border in the side menu

**Comment by strambc** [comment]
@Akramhar CONDENSER NOW TURNS UPSIDE DOWN
Everything else is solved

**Comment by Akramhar** [comment]
solved in 0.39
