### ISSUE TITLE
Tier check is missing --> this affects MicroscopeTableSettings, MicroscopeStandsettings, Channel/LightPath/Dichroic

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#245]
MicroscopeTableSettings appear RED at Tier 1 while it should be inactivated
MicroscoepStandSettings appear GREEN at Tier 1 while it should be inactivated
Channel/Dichroic appears GREEN at Tier 1 and it behaves as if the Settings could be added but they cannot

In all cases when one attempts to edit settings the application does not allow to Confirm

**Comment by Akramhar** [comment]
should be done in 0.37
