### ISSUE TITLE
ALERT MODEL CHANGE --> Fluorophore model changes

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#246]
1. Order of fields: ConcentrationUnit was positioned right after Concentration
2. Concentration description was changed
3. Fluorophore/FluorescentLabelType/ enumeration change

New enumeration list
Nucleic Acid_Aptamer motif Nucleic Acid_Bacteriophage-derived RNA tag, Nucleic Acid_Chemical Modification, Nucleic Acid_dCas9, Nucleic Acid_Molecular Beacon, Nucleic Acid_Organic dye, Protein_Biarsenical dye, Protein_Biological fluorophore, Protein_Fluorescent protein, Protein_Organic dye_Aspecific, Protein_Organic dye_Immunological targeting, Protein_Organic dye_Specific, Protein_Self-Labelling EnzymeTag, Quantum Dots, None, Other

**Comment by Akramhar** [comment]
should be done in 0.37
