### ISSUE TITLE
Saving items position when saving mic

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#25]
At the moment the position of the components is lost and when the microscope is opened it looks horrible.

**Comment by Akramhar** [comment]
We need to review this together, when i try this the position is -more or less- maintained.
There may be some other issue that affect this somehow

**Comment by strambc** [comment]
When the window gets resized it is all messed up.
Also make sure the larger canvas is incorporated in the new version so that we can check if that improves matters

**Comment by Akramhar** [comment]
Move to #33
