### ISSUE TITLE
Channel validation: even if all elements appear to have been selected and filled in DOT remains RED

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#250]
![image](https://user-images.githubusercontent.com/4050585/111087066-ed6b0580-84f5-11eb-81a9-81d71b0b6a88.png)

![image](https://user-images.githubusercontent.com/4050585/111087054-e3490700-84f5-11eb-920d-a0156530fbf3.png)

**Comment by Akramhar** [comment]
should be solved in 0.37
