### ISSUE TITLE
List of "Current component in this slot" appearance has to be change: make more space and remove scrolling bars

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#252]
The scrolling bars are very awkward and should be removed.
Elements should appear side by side etc.
![image](https://user-images.githubusercontent.com/4050585/111087151-505c9c80-84f6-11eb-981c-0af227f85be7.png)

**Comment by Akramhar** [comment]
should be solved in 0.37
