### ISSUE TITLE
TimeStamp-Increment: should allow float and need a unit

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#254]
TimeStamp-Increment should allow float values
Have to add a unit field

**Comment by Akramhar** [comment]
float is done, unit is bee agreed to specify in help

**Comment by strambc** [comment]
WEIRD GUI APPEARANCE

![image](https://user-images.githubusercontent.com/4050585/111372169-af462100-8670-11eb-8cad-19f7bec050c7.png)

**Comment by Akramhar** [comment]
solved in 0.39
