### ISSUE TITLE
Channel/Add Additional Element: Cannot delete elements once added

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#257]
Add one element (MagnificationChanger)
Added another element (Tube lens)

Appeared 2x TubeLens

Clicked to delete, did not disappear, Confirmed opened again, one element was missing, deleted a second element and had again to exit to see it gone. Last element could be deleted

**Comment by strambc** [comment]
https://user-images.githubusercontent.com/4050585/111097782-8e6ab800-8518-11eb-9135-2abacb37ff99.mov

**Comment by Akramhar** [comment]
should be solved in 0.37
