### ISSUE TITLE
ALERT MODEL CHANGE --> Extended enumeratino list for Objective/Correction

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#268]
New enumeration list

Achro, Achromat, Achroplan, Acroplan, Apo, Apochromat, C-Acroplan, EF, Fl, Fluar, Fluor, Fluotar, Lambda, N, Neofluar, NPL, Pl, Plan, Plano, PlanApo, PlanApochromat, PlanFluor, PlanNeofluar, SuperFluor, UPLAN, UPlanApo, UPlanFl, UV, VioletCorrected, Other

**Comment by Akramhar** [comment]
should be done in 0.37
