### ISSUE TITLE
Component nr. or name on GUI

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#27]
Any chance the name of the component could be written under the icon after confirm?
This would massively improve usability.

**Comment by Akramhar** [comment]
I think this is important, I'm going to try to implement this asap and get it released in 0.0.6

**Comment by Akramhar** [comment]
the name is now displayed in a small font under the component in the canvas, should go online in version 0.0.6
