### ISSUE TITLE
Manage Settings EditImagingSetting, TableSettings, MicroscopeStandSet

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#277]
Default state upon opening should be NO DOT.
If selected item and added and missing settings attributes RED DOT
When validated GREEN DOT

**Comment by Akramhar** [comment]
should be solved in 0.39

**Comment by strambc** [comment]
This is still present in v040

**Comment by Akramhar** [comment]
should be solved in 0.41
