### ISSUE TITLE
Manage Settings --> Edit Tooltip text

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#278]
- [x]  **MISSING** Edit Channel Settings -->  "Click this button to enter or edit general information about this image Channel."

- [x] **NOT CORRECT** Select Light Source -->  "Click this button to select the Light Source that was used for the acquisition of this Channel. After confirming the selection, click on the selected Light Source one more time to enter or edit the settings that were applied to it during acquisition."

- [x]  **NOT CORRECT**  Select Detector -->  "Click this button to select the Detector that was used for the acquisition of this Channel. After confirming the selection, click on the selected Detector one more time to enter or edit the settings that were applied to it during acquisition."

=====
- [x] Manage Settings/Open file selector --> "Open Microscope file selector: Choose the source of the Microscope file you want to use and that describes the Instrument that was used for the acquisition of the image(s) you want to annotate."

- [x] Manage Settings/Continue (1st button) --> "Continue: Click this button to select the image(s) you want to annotate and, if available, an existing Settings file."

- [x] Manage Settings/"Load Settings file selector" (currently "Create mode selector") --> Load Settings file selector: SAME TEXT BUT ADD Missing spaces after periods

- [x] Manage Settings/"Load from repository" selector --> "Select the Settings file you want to load."

- [x] Manage Settings/Continue (2st button) --> "Continue: Click this button to create a new Settings file or edit an existing one using the modality chosen above."

-----
- [x] Edit Imaging Environment --> "Click this button to select the Imaging Environmental Control Device that was used, and enter or edit information about the environment in which the biological sample was maintained during the acquisition of this Image."

- [x] Edit Microscope Table Settings --> "Click this button to select the Microscope Table, and enter or edit the settings that were applied to the Microscope Table for the acquisition of this Image."

- [x] Edit Microscope Stand Settings --> "Click this button to enter or edit information about the Settings that were applied to the Microscope Stand during the acquisition of this Image."

- [x] Edit Sample Positioning Settings --> "Click this button to select one or more Sample Positioning devices, and enter or edit the settings that were applied to them during the acquisition of this Image."

- [x] Edit Planes --> "Click this button to enter or edit general information about the Image Planes."

- [x] Add multiple planes --> "In case information about the Image Planes have not been imported automatically with BioFormats, click this button to easily add multiple related Planes to this Image."

- [x] Edit Channels --> "Click this button to enter or edit general information about the image Channels and about the light path associated with each of them."

----

- [x]  Add additional element(s) --> "If applicable, click this button to select one or more additional optical element or device that was used in this position to build the light path for this Channel."

- [x] Select Coupling Lens -->  "If applicable, click this button to select the Coupling Lens that was used for the acquisition of this Channel."

- [x] Select Light Source Coupling -->  "If applicable, click this button to select the Light Source Coupling device that was used for the acquisition of this Channel."

- [x] Select Relay Lens -->  "If applicable, click this button to select the Relay Lens that was used for the acquisition of this Channel."

- [x] Select Excitation Wavelength -->  "Click this button to select the Excitation Filter used for the acquisition of this Channel."

- [x] Select Emission Wavelength -->  "Click this button to select the Emission Filter used for the acquisition of this Channel."

- [x] Select Dichroic-->  "Click this button to select the Dichroic (or Beamsplitter) that was used for the acquisition of this Channel. After confirming the selection, click on the selected Dichroic or (Beamsplitter) one more time to enter or edit the settings that were applied to it during acquisition."

**Comment by Akramhar** [comment]
should be done in 0.39

**Comment by strambc** [comment]
@Akramhar THREE MISSING ITEMS

**Comment by Akramhar** [comment]
should be solved in 0.40
