### ISSUE TITLE
Manage Settings: Changes to text in Channel/LightPath GUI

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#279]
- [x] Change text to all "Add additional element" buttons to "Add additional elements)"
- [x] Add "Fluorescence Light Path" to bottom rectangle
- [x] Make sure Em/Ex and Dich do not cross over into bottom rectangle when element selected

**Comment by Akramhar** [comment]
should be done in 0.39

**Comment by strambc** [comment]
@Akramhar Text is Filter Set and should be "Fluorescence Light Path"

**Comment by Akramhar** [comment]
should be done in 0.40

**Comment by strambc** [comment]
DONE but the text spills over a bit ugly

![image](https://user-images.githubusercontent.com/4050585/111750212-52fa2180-8869-11eb-88ff-43b520254e39.png)

**Comment by Akramhar** [comment]
should be solved in 0.41
