### ISSUE TITLE
micron symbol messed up

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#28]
In UnitsOfLenght (and other similar instance) the µ symbol is not properly interpreted.
Can this be fixed? Or should we spell micro- out?

**Comment by Akramhar** [comment]
I'm going to try to get this fixed, not sure if its easily doable

**Comment by Akramhar** [comment]
should be solved in 0.0.6

**Comment by strambc** [comment]
This issue was closed.
However issue #51 might be connected.
