### ISSUE TITLE
ALERT MODEL CHANGE --> AcquisitionDate to Attribute and description change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#280]
Image/AcquisitionDate was changed from Element to Attribute to facilitate implementation by MMA and description was changed

**Comment by Akramhar** [comment]
should be in 0.39

**Comment by strambc** [comment]
RUN MODEL UPLOAD AGAIN BECAUSE I CHANGED THE DESCRIPTION

**Comment by Akramhar** [comment]
should be done in 0.39
