### ISSUE TITLE
ALERT MODEL CHANGE --> Changed enumeration list for Laser/Type

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#291]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Laser <br/>

**Current Field name:** Type <br/>

**Source of change (e.g., #XXX issue with change request):** Internal

**Brief description of the change (short and compelling):** The enumeration list for Laser/Type was missing key values

**Current Field enumeration value(s):** Chemical,   Dye, Gas, MetalVapor, OpticalParametricOscillator, SolidState,   SemiconductorLaserDiode, Other <br/>

**New Field enumeration value(s)**: Added --> DiodePumpedSolidState (DPSS) <br/>

**New list:** --> Chemical, DiodePumpedSolidState (DPSS), Dye, Gas, MetalVapor, OpticalParametricOscillator(OPS), SolidState, SemiconductorLaserDiode, Other

**Comment by Akramhar** [comment]
should be done in 0.41
