### ISSUE TITLE
ALERT MODEL CHANGE --> Objective/CorrectionCollar enumeration added "Multi" value and changed Description accordingly

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#292]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Objective <br/>

**Current Field name:** CorrectionCollar <br/>

**Source of change (e.g., #XXX issue with change request):** Internal <br/>

**Brief description of the change (short and compelling):** 
Noticed that it is possible for Objectives to have more than one CorrectionCollar.
Added the value "Multi" to the enumeration list and changed Description to explain.

Current Field description: This field records the type of Correction Collar with which this Objective is fitted. <br/>
**New Field description**: This field records the type of Correction Collar with which this Objective is fitted. In case the Objective has more than one Correction Collar please enter "Multi" and provide more details in Description.

Current Field enumeration value(s): Coverglass  Thickness, Immersion Liquid, Numerical Aperture, Temperature <br/>
**New Field enumeration value(s)**: Coverglass  Thickness, Immersion Liquid, Numerical Aperture, Temperature, Multi

**Comment by Akramhar** [comment]
should be done in 0.41
