### ISSUE TITLE
ALERT MODEL CHANGE --> Removed DetectorSettings/Zoom

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#293]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** DetectorSettings <br/>

**Current Field name:** Zoom <br/>
**New Field name: REMOVE FIELD**

**Source of change (e.g., #XXX issue with change request):** Internal <br/>

**Brief description of the change and its rationale (short and compelling):** A Detector cannot provide hardware-based Zoom. This field is therefore inappropriate. <br/>

**Comment by Akramhar** [comment]
should be done in 0.41
