### ISSUE TITLE
ALERT MODEL CHANGE --> Pixels/PixelType description and enumeration list change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#295]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** Pixels <br/>
**Current Field name:** PixelType <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** Description was incorrect and enumeration list lacked key values <br/>

Current Element/Field description: "This field records the variable type used to represent the Pixel Intensity in the Image."<br/>
New Element/Field description: "This field records the data type used to represent the Pixel Intensity in the Image."

Current Field enumeration value(s): lacked int14 and uint14 <br/>
New Field enumeration value(s): bit, complex, double, double-complex, float, int8, int12, int14, int16, int32,   uint8, uint12, uint14, uint16, uint32, Other

**Comment by Akramhar** [comment]
should be done in 0.41
