### ISSUE TITLE
ALERT MODEL CHANGE --> Detector/ElectronConversionFactor description change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#296]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** DetectorGroup <br/>

**Current Field name:** ElectronConversionFactor <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** Description was made more clear and consistent with that of DetectorSettings/AnalogGain<br/>

**New Field description:** "This field records the Electron-Conversion Factor for this Detector, as specified by the Manufacturer. The Electron Conversion Factor relates the actual number of electrons generated by the Detector with the digital number associated with each Pixel. It is expressed in electrons/Analog-to-Digital-Unit (ADU). Note that ADU can also be referred to as Digital Number (DN) or Binary Number. It is sometimes referred to as Digital Gain or, in case of CCD cameras as CCD Gain."

**Comment by Akramhar** [comment]
should be done in 0.41
