### ISSUE TITLE
ALERT MODEL CHANGE --> DetectorSettingsGroup/AnalogGain description change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#297]
Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.

Current Element name: DetectorSettingsGroup

Current Field name: AnalogGain

Source of change (e.g., #XXX issue with change request): INTERNAL

Brief description of the change and its rationale (short and compelling): Description was made more clear and consistent with that of Detector/ElectronConversionFactor

New Field description: "This field reports the Analog Gain (also known as Inherent Gain or simply as Gain) that was applied during the Acquisition of this Image. The Analog Gain is a property Inherent to the Detector and it specifies how many electrons correspond to 1 signal unit (photon) detected. Gain is reported in terms of electrons/Analog-to-Digital-Unit (ADU). A gain of 8 means that the Detector digitizes the light signal so that each 8 photoelectron produces 1 ADU. NOTE: In the case of Point Detectors the value of Analog Gain can be set freely by the user. Conversely, in the case of Cameras, it is common for the Gain to be preset by the Manufacturer to minimize noise. In this case, either the Analog Gain cannot be changed or the user is given the choice of selecting between a few preset Analog Gains values upon Acquisition. Finally, several Cameras might have so-called Automatic Gain Control (AGC or AutoGain) that will automatically adjust so the full range of the Analog-to-Digital Converter (ADC) is used. Unless you can turn off the AGC, the use of these Cameras is highly discouraged for quantitative work."
@strambc

**Comment by Akramhar** [comment]
should be done in 0.41
