### ISSUE TITLE
ALERT MODEL CHANGE --> DetectorGroup/MaxBitDepth enumeration and description change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#298]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** DetectorGroup <br/>

**Current Field name:** MaxBitDepth <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** Description was made more clear and consistent with that of CameraSettings/DigitizerBitDepth. The enumeration list was changed by employing the simple type "DigitizerType" to make it consistent with CameraSettings/DigitizerBitDepth <br/>

**New Element/Field description**: "This field records the Maximum Bit Depth provided by the Detector's Analog to Digital Converter (ADC; also referred to as Digitizer)."

Current Field enumeration value(s): lacked  4bit, 32bit, 64bit <br/>
**New Field enumeration value(s):** 8bit, 12bit, 14bit, 16bit, 32bit, 64bit

**Comment by Akramhar** [comment]
should be done in 0.41
