### ISSUE TITLE
ALERT MODEL CHANGE --> CameraSettings/DigitizerBitDepth enumeration and description change

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#299]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** CameraSettings <br/>

**Current Field name:** DigitizerBitDepth <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** Description was made more clear and consistent with that of DetectorGroup/MaxBitDepth. Values were added to the enumeration list <br/>

**New Element/Field description:** "If selectable, this field reports the Effective Bit Depth that was used by the Detector's Analog to Digital Converter (ADC; also referred to as Digitizer) for the Acquisition of this Channel."

Current Field enumeration value(s): lacked  4bit, 32bit, 64bit <br/>
**New Field enumeration value(s):** 8bit, 12bit, 14bit, 16bit, 32bit, 64bit

**Comment by Akramhar** [comment]
should be done in 0.41
