### ISSUE TITLE
ALERT MODEL CHANGE --> CameraSettings/DigitizerBitDepth moved to DetectorSettingsGroup and changed name

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#300]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** CameraSettings <br/>
**Current Field name:** DigitizerBitDepth <br/>

**MOVED TO --> DetectorSettingsGroup**
**New Field name:** EffectiveBitDepth <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** The location of the field and its name was changed to make it consistent with DetectorGroup/MaxBitDebth <br/>

**Comment by Akramhar** [comment]
should be done in 0.41
