### ISSUE TITLE
[BUG] MANAGE SETTINGS --> Add Αdditional Elements  --> elements appear duplicated after addition

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#302]
**Describe the bug**
Elements were added using Add additional elements.
After returning to same place elements appear duplicated.

**To Reproduce**
1. Go to 'EditChannels --> Edit selected Channel (405 Channel)
2. Click on Add additional element
3. Confirm
4. Save
5. Back and enter again
6. Go back to same place as 2
4. See  elements that had been added previously appear duplicated

**Expected behavior**
Elements should appear in the number and order they had been saved

**Screenshots**
![image](https://user-images.githubusercontent.com/4050585/111753747-99517f80-886d-11eb-9e17-8351dd7c2a38.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version [e.g. 22]: v040

**Comment by Akramhar** [comment]
seems to be related to #290, should be solved in 0.41
