### ISSUE TITLE
[BUG] MANAGE INSTRUMENT/SETTINGS --> SamplePositioningSettings added to all added elements

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#303]
**Describe the bug**
When entering Attribute value in SamplePositioningSettings is added to all added elements

**To Reproduce**
1. Go to SamplePositioningSettings
2. Add multiple elements
3. Enter a value in one of the Settings
4. Same value appears in the same position in all elements

**Expected behavior**
Each element should have different attribute values

https://user-images.githubusercontent.com/4050585/111755920-0534e780-8870-11eb-91dc-bb5a6381be6f.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Version [e.g. 22]: v040

**Comment by strambc** [comment]
Only affects elements that have already been added

**Comment by Akramhar** [comment]
should be solved in 0.41
