### ISSUE TITLE
[BUG] MANAGE SETTINGS --> SamplePositioning remove one prev added element remaining became red

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#304]
**Describe the bug**
After additing several elements in SamplePositioningSettings attempted to remove one.
All remaining became red.
No errror

**To Reproduce**
1. Go to SamplePositioningSettings
2. Add Elements
3. Enter value in Settings (optional) 
4. Confirm
5. Enter again
6. Attempt to remove one item
7. Remaing items are red

**Expected behavior**
Remaining items should remain green

**Screenshots**
![image](https://user-images.githubusercontent.com/4050585/111756457-9906b380-8870-11eb-9bea-3f9df3b27460.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version [e.g. 22]: 0.40

related to #303

**Comment by strambc** [comment]
Confirmed
Clicked again 
Now all elements are gone

![image](https://user-images.githubusercontent.com/4050585/111756619-cce1d900-8870-11eb-81bd-ae7551ff7931.png)

**Comment by strambc** [comment]
Attempted to add elements again, will only allow to add one. Cannot add more

![image](https://user-images.githubusercontent.com/4050585/111756767-f7cc2d00-8870-11eb-8658-479f8dc2ea38.png)

**Comment by strambc** [comment]
Exited without saving
Entered again
Elements are back in their place and it is possible to delete one with all the left ones remaining green

![image](https://user-images.githubusercontent.com/4050585/111756995-382bab00-8871-11eb-9ae8-d71379854627.png)

**Comment by strambc** [comment]
Value that had been entered before #303 not present

**Comment by strambc** [comment]
Strange red dot behavior starts again after confirming and getting back in.

**Comment by Akramhar** [comment]
should be fixed in 0.41
