### ISSUE TITLE
ALERT MODEL CHANGE --> DichroicGroup removed FilterHolderPosition

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#305]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name:** DichroicGroup<br/>

**Current Field name:** FilterHolderPosition <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** FilterHolderPosition was redundant with OpticsHolderPosition present in MirroringDeviceGroup and was removed <br/>

**REMOVED FIELD**

**Comment by Akramhar** [comment]
should be done in 0.41
