### ISSUE TITLE
ALERT MODEL CHANGE --> AttenuationCoefficient field made optional in Filter, Dichroic, Lens, AcoustoOpticalDevice, ElectroOpticalDevice

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#306]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name(s):** Filter, Dichroic, Lens, AcoustoOpticalDevice, ElectroOpticalDevice <br/>

**Current Field name:** AttenuationCoefficient <br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** It was noticed that very rarely for this information is provided by manufacturers making it impossible for users to report it. It was therefore made optional for the time being. <br/>

Current Field requirement level: Required <br/>
**New Field requirement level: Optional**

**Comment by Akramhar** [comment]
should be done in 0.41
