### ISSUE TITLE
ALERT MODEL CHANGE --> OpticalApertureGroup/OpticsHolderPosition was made optional

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#309]
**Report an approved change to existing metadata model structure, elements, fields names, descriptions, data types, cardinality, requirement level, and/or enumeration values.**

**Current Element name(s):** OpticalApertureGroup <br/>

**Current Field name:** OpticsHolderPosition<br/>

**Source of change (e.g., #XXX issue with change request):** INTERNAL <br/>

**Brief description of the change and its rationale (short and compelling):** It was noticed that this information does not warrant a high requirement level. It was therefore made optional. <br/>

Current Field requirement level: Required <br/>
**New Field requirement level: Optional**

**Comment by Akramhar** [comment]
should be done in 0.41
