### ISSUE TITLE
Focusing vs. Stage

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#32]
Noticed there is a discrepancy between STAGE vs. FOCUSING in the model.
Currently Focusing extends Stage and all elements that belong to the Focusing group are of Focusing type.

However there are in fact two categories:

1) Stage (Mechanical and Piezo)
2) Focusing (Turrett and Piezo).

I would like to reorganize with nested groups (similar to Detector --> Camera).

Focusing group contains
1) ObjectiveTurrett
2) Piezolelectric Objective
3) PositioningDeviceGroup

PositioningDeviceGroup contains:
1) Mechanical Stage
2) Piezoelectric Stage

This way the user would not have to enter a lot of NOT APPLICABLE when filling in Focusing devices and only enter X and Y movement when applicable.

Would this create a lot of problems on your hand?

C

This way it would make more sense for users to fill in informations because

**Comment by Akramhar** [comment]
Do these components share common attributes than we can extrapolate in a super class?
I understand the need for convenience but the detector / camera categories are created based on the model, because detector has a set of attributes that are shared by some components and camera has the same.
Doing it arbitrarily just to have components displaying in a different way it would feel, in my opinion, like ruining the model.

**Comment by strambc** [comment]
It would not be arbitrary: it would be the separation of STAGE vs FOCUSING-DEVICE.
FOCUSING-DEVICE ONLY MOVE up and down
STAGE potentially moves in all direction (including up and down).
In this sense, STAGE IS-A FOCUSING-DEVICE.
Here is what I propose:

![Screen Shot 2019-06-13 at 16 04 25](https://user-images.githubusercontent.com/4050585/59463900-0a404980-8df5-11e9-8b29-6dee40f4d685.png)

**Comment by Akramhar** [comment]
Ok, needs to be modified in the model and tested out

**Comment by strambc** [comment]
Change made in v01-06
The new model is as follows:

![Screen Shot 2019-06-17 at 22 50 49](https://user-images.githubusercontent.com/4050585/59649991-8b2f7600-9152-11e9-90d0-42758563cd72.png)

Categories names were changed as follows:

![Screen Shot 2019-06-17 at 22 53 17](https://user-images.githubusercontent.com/4050585/59650069-ba45e780-9152-11e9-973f-651bf2e1497e.png)

Image names were changed as follows (v.14.00)

![Screen Shot 2019-06-17 at 22 59 04](https://user-images.githubusercontent.com/4050585/59650315-89b27d80-9153-11e9-84be-4c0010899b12.png)
