### ISSUE TITLE
Re-sizing issue

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#33]
When resizing a component on the GUI, the whole window starts jittering.

https://www.dropbox.com/s/a9p6k0h42o1fobr/Jittering%20window%20upon%20re-sizing.mov?dl=0

**Comment by strambc** [comment]
This might have been a silent crash...
When the application was relaunched it did not reproduce.

**Comment by Akramhar** [comment]
You can see if there is a "crash" or problem by keeping the dev-tool opened (view -> toggle developer tools )
If red writings show up there then u can even copy and paste it in a text file and attach it here :)

**Comment by Akramhar** [comment]
From other resizing issue : Huge issue with resizing: sometimes when trying to increase size it collapses down and disappears.

**Comment by Akramhar** [comment]
From other resizing issue : At the moment the position of the components is lost and when the microscope is opened it looks horrible.

**Comment by Akramhar** [comment]
this should not be relevant anymore
