### ISSUE TITLE
Enumeration

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#35]
Should we add an "NA" entry or is it possible to leave it blank?
In some cases, it appears that it cannot be left blank (when a default value is provided).

**Comment by Akramhar** [comment]
leave it blank if it's not mandatory works perfectly fine.
if it's mandatory and doesn't have a default value it's going to force the user to pay attention.
if it does have a default value that's going to be used.
