### ISSUE TITLE
Issues when hitting Confirm

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#36]
When Confirm is clicked the GUI advances 2 tabs instead of one.

**Comment by Akramhar** [comment]
Yes this is a problem in how the errors are handled, need to spend some time in figuring out why this happens.

**Comment by strambc** [comment]
Other problem: does not let Confirm even when all fields are filled in.

**Comment by Akramhar** [comment]
this issue happens when the data loaded is not correctly pushed in the forms.
needs to be tested now, because I fixed some parts that could affect this

**Comment by strambc** [comment]
Seems to be solved
