### ISSUE TITLE
Confirm: does not work even when all fields are filled in

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#38]
This happened when going in and editing an existing Dichroic after it had been already confirmed

**Comment by strambc** [comment]
might be related with #36

**Comment by strambc** [comment]
When it happens again send saved microscope.

**Comment by strambc** [comment]
This problem happened again with CCD Camera in TESM Microscope.

USE CASE:
Use Electron version.
Open from repository --> CCD Camera appears red-boxed

[tesm_mma_el_91719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3623272/tesm_mma_el_91719.txt)

When open and hit confirm the GUI jumps to 

![Screen Shot 2019-09-17 at 16 32 54](https://user-images.githubusercontent.com/4050585/65078184-899c6680-d96a-11e9-9b48-bc7140b308ef.png)


![Screen Shot 2019-09-17 at 16 32 40](https://user-images.githubusercontent.com/4050585/65078069-404c1700-d96a-11e9-96d8-880015061d76.png)

**Comment by strambc** [comment]
**MICROSCOPE FILE**
Before change
[tesm_mma_el_91719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3623272/tesm_mma_el_91719.txt)

After change
[tesm_mma_el_91719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3623414/tesm_mma_el_91719.txt)

**Comment by strambc** [comment]
**SECOND USE CASE:**
Use the OMERO version.
Open the tesm_mma_el_91719.json (after change; see above) from file  --> CCD Camera appears red-boxed

![Screen Shot 2019-09-17 at 17 22 35](https://user-images.githubusercontent.com/4050585/65080839-34635380-d970-11e9-9dd3-c66076e91305.png)

When open and hit confirm the GUI jumps to CCD tab:

![Screen Shot 2019-09-17 at 17 22 47](https://user-images.githubusercontent.com/4050585/65080939-77252b80-d970-11e9-9ace-9ad45b0e66c2.png)

Going back to look the Camera tab the PixelWidthUnit and PixelHeightUnit fields now are filled in with "Ym" and show the "should be equal to one of the allowed values"  error.

![Screen Shot 2019-09-17 at 17 23 04](https://user-images.githubusercontent.com/4050585/65080972-8b692880-d970-11e9-8061-a809eaef8583.png)

When the field values are corrected to "µm":
![Screen Shot 2019-09-17 at 17 23 37](https://user-images.githubusercontent.com/4050585/65081162-fe729f00-d970-11e9-94ff-f28cd3a58012.png)

and the "Confirm" button is clicked, the GUI advances to the RelayLens tab and the window does not close:

![Screen Shot 2019-09-17 at 17 23 49](https://user-images.githubusercontent.com/4050585/65081226-2104b800-d971-11e9-8876-1506dec85768.png)

When you hit Cancel the red-box and the error above are still there.

![Screen Shot 2019-09-17 at 17 25 10](https://user-images.githubusercontent.com/4050585/65081288-4c87a280-d971-11e9-8af1-9fd04037fd7b.png)

**Comment by strambc** [comment]
Might be connected with #28, with #37 and with #41

**Comment by strambc** [comment]
***MICROSCOPE FILE***
After loading on OMERO and saving

[TESM_MMA_el_91719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3623551/TESM_MMA_el_91719.txt)

**Comment by Akramhar** [comment]
@strambc  is this still relevant?

**Comment by Akramhar** [comment]
i think most of this should be fixed in 0.18, should be noted that some stuff have been reworked and the components that don't currently validate should be removed and re created due to some changes in the code

**Comment by strambc** [comment]
Seems solved
