### ISSUE TITLE
Filter and Dichroic: Saving different values in different TR and RR elements

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#39]
After adding multiple TR and RR elements the different values for each element are not saved: they are all identical to each other.
Not clar if first or last value entered is saved.

**Comment by Akramhar** [comment]
should be solved in 0.0.6 needs to be tested

**Comment by strambc** [comment]
This issue was solved with TR but not with RR.
This issue was closed and another one was created to better describe the current problem.

#45
