### ISSUE TITLE
Change button text: "Edit components" --> "Edit band-pass component"

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#44]
Change the text of the "Edit components" button to --> "Add band-pass component"

**Comment by Akramhar** [comment]
I changed it to "Edit band-pass components"  instead of "Add" because you can remove them too.
@strambc What do you think?

**Comment by Akramhar** [comment]
Changed to Add/Remove band-pass, otherwise it wouldn't fit in the button
