### ISSUE TITLE
Error with saving: Dichroic does not save content of TR fields when RR components are present

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#45]
Does not save CutIn, CutOut, and Transmittance or TR elements in Dichroic.
When hitting Confirm, it allows closing, the red box goes away, but the content of fields is not retained.

Opened in TIer5
Validate in Tier5

[tesm_mma_ome_9719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3603071/tesm_mma_ome_9719.txt)

![Screen Shot 2019-09-11 at 19 13 32](https://user-images.githubusercontent.com/4050585/64742075-f4602480-d4c8-11e9-85de-195a481ea737.png)
![Screen Shot 2019-09-11 at 19 19 04](https://user-images.githubusercontent.com/4050585/64742120-12c62000-d4c9-11e9-9bf0-27e8ab437d12.png)

**Comment by strambc** [comment]
Software version: alpha_0.0.15b

**Comment by strambc** [comment]
Removed problem Dichroic
Created a new one.
Same issue presented again.

![Screen Shot 2019-09-11 at 19 37 16](https://user-images.githubusercontent.com/4050585/64742858-ae589000-d4cb-11e9-9197-3e2bd4fdd8d0.png)

**Comment by strambc** [comment]
Attempted to fix by removing RR elements in the same Dichroic component.
Did not work.

REMOVED Dichroic and did not create any RR components (just 3 TR components) and:

**Comment by strambc** [comment]
Created new Dichroic element (3 TR and 3 RR components) and the same problem presented.
Realized that what happens is that the CutIn and CutOut values in the corresponding RR components get copied over to the TR (i.e. RR1 --> TR1 etc.).
However the same does not happen with Reflectance vs. Transmittance. The value in Transmittance gets erased and not replaced with the value in Reflectance.

Attempted to remove RR elements and the same problem persisted.
Attempted to create a new Dichroic without any RR components (just 3 TR) and the issue went away.

**Comment by Akramhar** [comment]
should be fixed in 0.18
