### ISSUE TITLE
Validation issue nr. 2

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#48]
In certain occasions even though an element was validated, when the microscope is opened again, the Tier validation gets lost: some fields in the element are lost and need to be re-entered.
Have not pinpointed an exact use case in which this happens.

**Comment by Akramhar** [comment]
needs to be re-evaluated after modification in 0.18

**Comment by strambc** [comment]
Did not observe yet but will leave it open until testing more extensively
