### ISSUE TITLE
LightGuide, Detector, Prism, PolarizationOptics--> WavelengthRange tab is missing

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#50]
LightGuide is associated with **1 and only 1** WavelenghtRange sub-element.
HOWEVER --> On the GUI the **"WavelengthRange"** tab is missing.
In addition, the **"Edit component"** button is grey and not functional and therefore it is not possible to add any WavelenghtRange components.

This might be connected with closed issue #19

**Comment by strambc** [comment]
Same applies to 
-- Detector (has 0 to 1 "WavelengthRange")
-- PolarizationOptics (has 0 to 1 "WavelengthRange")
-- Prism (has 0 to 1 "WavelengthRange")

**Comment by Akramhar** [comment]
this should be fixed in 0.18
