### ISSUE TITLE
Issue with PiezoElecticObjective focusing device

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#51]
This might be connected with closed issue #28 

USE CASE

Created TESM microscope (tesm_mma_el_91719) using Electron stand-alone version.
PiezoElecticObjective --> "ZTravelRangeUnit" was assigned "µm".

![Electron_micron](https://user-images.githubusercontent.com/4050585/65074283-856c4b00-d962-11e9-8d63-9a575a8b8f71.png)

TESM was saved as: 

--> [tesm_mma_el_91719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3623125/tesm_mma_el_91719.txt)

When this was opened in OMERO the "PiezoElectricObjective " appeared as un-validated (red boxed), when clicking Confirm the GUI advances to the "Sample Positioning" tab and shows that in the "ZTravelRangeUnit" field was assigned "Ym"

![Electron-OMERO_micron](https://user-images.githubusercontent.com/4050585/65074314-91580d00-d962-11e9-9229-c21c7f187518.png)

![Electron-OMERO_micron-2](https://user-images.githubusercontent.com/4050585/65074323-95842a80-d962-11e9-8893-58f30bd5c347.png)

**Comment by strambc** [comment]
When the "ZTravelRangeUnit" field was corrected to "µm", the microscope was saved and it was re-opened then the problem goes away

![Electron-OMERO-correct-save-reopen](https://user-images.githubusercontent.com/4050585/65074484-eeec5980-d962-11e9-8022-5478a4b7ff90.png)

**Comment by strambc** [comment]
When the PiezoElecticObjective --> "ZTravelRangeUnit" field is assigned "mm", the problem does not appear:

![Electron-OMERO_millimiter](https://user-images.githubusercontent.com/4050585/65074556-1a6f4400-d963-11e9-88b9-74004a8ad602.png)

**Comment by Akramhar** [comment]
this seems to be fixed in 0.18

**Comment by strambc** [comment]
Need to test when v18 is in OMERO
