### ISSUE TITLE
 Add graphical guides on Microscope body image

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#53]
This issue inherits from:
https://github.com/WU-BIMAC/MicroscopyMetadata4DNGuidelines/issues/7

Add graphical guides to the main microscope window.
This would facilitate the positioning of a component on the canvas
They could become interactive.

**Comment by Akramhar** [comment]
is this still relevant given the new canvas? i guess we can close this an open a follow-up nice to have feature for the future to make the canvas slots interactive
