### ISSUE TITLE
v0016 Component jump after dragging

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#56]
Electron version v0016
Microscope tesm_mma_el_91719.json
[tesm_mma_el_91719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3786927/tesm_mma_el_91719.txt)

Opened the microscope from the repository
Scrolled all the way right and attempted to reposition one of the "LightSources"
The icon jumped back left (see screenshot)

<img width="1405" alt="Screen Shot 2019-10-30 at 12 13 05 AM" src="https://user-images.githubusercontent.com/4050585/67829024-f21f4d00-faab-11e9-9f3d-03f0171a2c21.png">
<img width="1399" alt="Screen Shot 2019-10-30 at 12 13 34 AM" src="https://user-images.githubusercontent.com/4050585/67829025-f21f4d00-faab-11e9-990b-827c66ffad39.png">

**Comment by Akramhar** [comment]
Seems the mac version didn't get the upgrade
Gonna release another one right now

**Comment by strambc** [comment]
Ok this is fixed
