### ISSUE TITLE
Resizing does not get saved

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#57]
v0016-1
Electron stand-alone for Mac
tesm_mma_el_103019.json
[tesm_mma_el_103019.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3791963/tesm_mma_el_103019.txt)

When items are resized, microscope saved, back and re-open
the items do not retain the new size but go back to the original size

**Comment by strambc** [comment]
Update: it appears that in both Electron and OMERO version the saving of re-sizing issue is limited to making an icon smaller.
It will save making an item bigger but not smaller.
In OMERO when the microscope is initially loaded the correct, smaller size is displayed for a fraction of a second and then it resizes back to default.

[tesm_mma_el_103019.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3795438/tesm_mma_el_103019.txt)

**Comment by Akramhar** [comment]
this should be fixed in 0.18, correct?
