### ISSUE TITLE
Sporadic component jumping issue

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#58]
v0016-1
Electron stand-alone for Mac
tesm_mma_el_103019.json
[tesm_mma_el_103019.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3791963/tesm_mma_el_103019.txt)

Ex-Filter - Empty
Attempted to overlay onto Filter Cube 1 and the item jumped to the bottom - left
Then attempted to reposition another item and it also jumped.
Then it started working again.
Difficult to understand what triggered the issue and what triggered the fix

**Comment by strambc** [comment]
Happened again with Cube1Dich
Jumped down and left
Same happened with one of the Filter wheel Em-Filters
Then it got restored

**Comment by strambc** [comment]
Happened again with FilterSet Cube 6
and then with TESM Cube6Em

<img width="1400" alt="Issue_#56" src="https://user-images.githubusercontent.com/4050585/67916497-4558d480-fb6c-11e9-9987-743bbf3bc2da.png">
<img width="1223" alt="Issue_#56_2" src="https://user-images.githubusercontent.com/4050585/67916501-4984f200-fb6c-11e9-8a9c-7d6989a90002.png">

**Comment by strambc** [comment]
[2019-06-17_Strambio_NewEgg order.pdf](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3792063/2019-06-17_Strambio_NewEgg.order.pdf)

**Comment by strambc** [comment]
Really difficult to decipher
One common theme is that when it starts jumping then it jumps a couple more times until it is moved to a "safe" position and then it stops jumping

**Comment by strambc** [comment]
It happened 7 times in one session

**Comment by strambc** [comment]
Microscope
microscope_template_2.json

Moved Relay Lens and it jumped all the way down as if the canvas was twice as high and microscope was in the top left

**Comment by Akramhar** [comment]
this needs to be verified in 0.18 to see if it's still relevant

**Comment by strambc** [comment]
Did not observe yet but will leave it open until testing more extensively
