### ISSUE TITLE
Tab disappear

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#59]
It happened a number of times
While entering values and hitting Confirm the tabs on top of the window disappear.
I have to close and then re-open and enter values all over again
<img width="1071" alt="Issue_#57" src="https://user-images.githubusercontent.com/4050585/67919355-67efeb00-fb76-11e9-87fa-86eae3875d4e.png">

**Comment by Akramhar** [comment]
is this still happening? can you give me a use case to reproduce?

**Comment by strambc** [comment]
Did not observe yet but will leave it open until testing more extensively
