### ISSUE TITLE
Validation Issue #3

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#60]
v0016-1
[tesm_mma_el_103019.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3795740/tesm_mma_el_103019.txt)

The microscope was saved yesterday and reopened a number of times on Electron.
The validation issue with Camera (which had been ongoing) appeared to be fixed.

When the same file opened on OMERO the Camera + PiezoElectric Focus showed up as non-validated (red boxed)

Was able to fix the PiFoc issue but not the Camera issue which remained red-boxed.
See below for screen shots

![image](https://user-images.githubusercontent.com/4050585/68451459-d5c29500-01bc-11ea-931e-9d10c05347f0.png)

**Comment by strambc** [comment]
<img width="1311" alt="Issue_#60_0" src="https://user-images.githubusercontent.com/4050585/67986161-cc578c80-fc00-11e9-839b-7b718841eff9.png">
<img width="1213" alt="Issue_#60_1" src="https://user-images.githubusercontent.com/4050585/67986168-ce215000-fc00-11e9-8154-cab6b814c1d6.png">
<img width="1213" alt="Issue_#60_2" src="https://user-images.githubusercontent.com/4050585/67986173-cfeb1380-fc00-11e9-9a28-290f6c19e279.png">
<img width="1213" alt="Issue_#60_3" src="https://user-images.githubusercontent.com/4050585/67986181-d2e60400-fc00-11e9-9940-66249a9cf039.png">
![Uploading Issue_#60_4.png…]()

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/68451438-c0e60180-01bc-11ea-8615-7c1b146379ac.png)

**Comment by Akramhar** [comment]
should be fixed in 0.18

**Comment by strambc** [comment]
Have to wait until v18 is on OMERO to test
