### ISSUE TITLE
TESM_MMA_el_110619 issues 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#61]
The TESM_MMA_el_110619 microscope that was previously saved appears to have issues with the size of the BOUNDING BOXES which do not resize according to the new sizes but retain the old size (see example)
![image](https://user-images.githubusercontent.com/4050585/69701670-6fde7480-10bb-11ea-8e68-0b717b53478a.png)

WOULD IT BE POSSIBLE TO FIX? 
If not I will have to rebuild the microscope from scratch (which might be a problem as I would like to use the screenshot for the poster)

**Comment by strambc** [comment]
The issue is not present with newly added elements:

![image](https://user-images.githubusercontent.com/4050585/69701812-cfd51b00-10bb-11ea-8fb6-644bfe6576ba.png)

**Comment by Akramhar** [comment]
if you resize the element to the max size it should get fixed automatically
