### ISSUE TITLE
Removing Dichroic prevents FilterSet Confirmation

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#63]
Created FilterSet
Created Dichroic
Reference Dichroic in FilterSet
Saved
Removed Dichroic
Red box does not appear
When attempting to edit the FilterSet it will not allow to Confirm, only Cancel is available

![image](https://user-images.githubusercontent.com/4050585/69767348-ce523400-1149-11ea-92b1-43eafbeef41c.png)

![image](https://user-images.githubusercontent.com/4050585/69767361-dc07b980-1149-11ea-86bc-755999f34d9b.png)

![image](https://user-images.githubusercontent.com/4050585/69767365-e1fd9a80-1149-11ea-9ba4-3a49e0063c01.png)

**Comment by Akramhar** [comment]
should be fixed in 0.19
