### ISSUE TITLE
Resizing bug: when trying to resize the new size gets stuck 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#65]
Working on Electron
On the last version of TESM 
[tesm_mma_el_112719.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/3906427/tesm_mma_el_112719.txt)

Attempting to resize, resizing goes wild and it becomes impossible to get hold of the object.
See examples belwo

**Comment by strambc** [comment]
**Examples:**

![Resizing issue 1_1](https://user-images.githubusercontent.com/4050585/69891128-2c0c8a80-12c8-11ea-9dd4-61663fae68ee.png)

![Resizing issue 1_2](https://user-images.githubusercontent.com/4050585/69891131-2f077b00-12c8-11ea-88f9-bc436d7ef8a8.png)

<img width="156" alt="Resizing issue 1_3" src="https://user-images.githubusercontent.com/4050585/69891132-3169d500-12c8-11ea-9ec1-2f5a739856e6.png">

**Comment by Akramhar** [comment]
there is a chance this may be fixed in 0.0.19, needs testing
