### ISSUE TITLE
All elements have Add/Remove Band Pass

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#67]
Was this done on purpose?

**Comment by Akramhar** [comment]
I tested it and the button to edit band-pass seems to be disabled for the elements that are not supposed to have band-pass. Are you experiencing something different?

**Comment by strambc** [comment]
Yes it is dibbled but I was wondering whether this was on purpose. I do not think it was there before…
Right?

**Comment by Akramhar** [comment]
Looking at the code, it should have, I didn't change how the buttons are created/positioned. I changed only how to enable/disable that specific button.

**Comment by strambc** [comment]
OK so now all elements have it and it is disabled if not relevant. Correct?
Is this how we want to have it?

**Comment by Akramhar** [comment]
we can try to remove it when not relevant in the next development round

**Comment by strambc** [comment]
Would remove it if possible
