### ISSUE TITLE
SVG & PNG Image Full Path Not Calculated Properly

### ISSUE THREAD

**Issue by utku-ozturk** [WU-BIMAC/4DNMicroscopyMetadataToolReact#70]
SVG & PNG image full path is miscalculated for the following case:

If `imagesPathPNG` and `imagesPathSVG` are passed explicitly via props instead of default "./assets/png/" (e.g. https://raw.githubusercontent.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/master/public/assets/svg/) and 4DNMicroscopyMetadataToolReact component is embedded into a site that uses https. (e.g. https://data.4dnucleome.org)

Then, the result full path has a missing "/": `https:/` instead of `https://` (e.g. https:/raw.githubusercontent.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/master/public/assets/svg/Transmitted_LightSource_GenericExcitationSource.svg?sanitize=true)

On the other hand, if the site uses `http` then image full path is calculated properly. (http://staging.4dnucleome.org is fine)

The possible solution would be 

1. url.resolve instead of path.join while combining full url from base path and file name. https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/blob/087c6bc67a057529b1c8cb9a045e5b41b4e43c13/src/components/toolbar.js#L83
2. simple string concatenation 

`url.resolve` and `path.join` url combine diff. sandbox here, pls check : https://codesandbox.io/s/utku-ozturk-wyshr

**Comment by Akramhar** [comment]
this should be solved in version 0.22
one note is that you need to setup the path with a / at the end otherwise url.resolve doesn't work properly (see [here](https://github.com/nodejs/node/issues/8921))

**Comment by utku-ozturk** [comment]
thanks @Akramhar, I'll test shortly and inform you.

**Comment by utku-ozturk** [comment]
@Akramhar image.path left on this line and should be replaced w/ url. resolve: https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/blob/406e7cd8840a914cfd7e31bee91a4cc79b820910/src/components/toolbar.js#L83

**Comment by Akramhar** [comment]
#71 should solve this, please let me know so I can close this issue :)

**Comment by utku-ozturk** [comment]
Will update the package in FF and if all set after deployment, then we would close the issue. I'll inform you @Akramhar.

**Comment by Akramhar** [comment]
@utku-ozturk was this solved? Can we close it?
