### ISSUE TITLE
Button rename

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#75]
Create Microscope >> Manage Instrument Hardware or Manage Hardware
Use Microscope >> Manage Image Acquisition Settings or Manage Acquisition Settings or Manage Settings

Choose one of the options depending on whether or not the text fit in the button without totally destroying the estetic of the GUI.

**Comment by strambc** [comment]
Validate @ tier: 1 >> Validate @ Tier 1
Save microscope >> Save Microscope file

**Comment by Akramhar** [comment]
I wrote on my notes "Manage Instrument" and "Manage Settings", i added that in version 0.23, let me know if that works.

**Comment by strambc** [comment]
Ok works

Caterina Strambio De Castillia, Ph.D. | CZI Imaging Scientist | Assistant Professor, Program in Molecular Medicine | University of Massachusetts Medical School |
——————————————
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On Jun 12, 2020, at 9:15 PM, Akramhar <notifications@github.com> wrote:

﻿

I wrote on my notes "Manage Instrument" and "Manage Settings", i added that in version 0.23, let me know if that works.

**Comment by Akramhar** [comment]
everything in this issue should be included in 0.23
