### ISSUE TITLE
Mouse over text to add

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#76]
### **Window 1**

**Browse** button >> "Click this button to navigate your file system and select a home folder that will contain your saved Microscope files. This folder will constitute your local Repository."

**Confirm** button >> "Click Confirm to continue."

###  **Window 2**
**Tier selector** >> "Tier selection: Choose the Tier level you want to utilize to document Instrument Hardware Specifications and Image Acquisition Settings. Please refer to the following link for more details about Tier definition: https://arxiv.org/ftp/arxiv/papers/1910/1910.11370.pdf"
**Manage Instrument** button >> "Manage Instrument Hardware: Click this button to create, load from a template, or edit a Microscope file describing the hardware components of the Instrument you want to document".
**Manage Settings" button >> "Manage Acquisition Settings: Click this button to select an existing Microscope file and enter, load from file, or edit the acquisition settings associated with the specific Image dataset you want to document".

### **Window 3 (Manage Instrument Hardware)**
**Create from scratch** selector >> "Choose the modality you want to use for Instrument hardware management. 'Create from scratch' allows you to create a brand new Microscope file from scratch. 'Load from file' allows you to import into Micro-Meta App a previously available Microscope file (i.e., an example file, a template file, or an existing Microscope file shared by a colleague) to edit. 'Load from repository' allows you to load a previously available file from the active Micro-Meta App repository."
**Confirm** button >> "Click Confirm to continue."
**Back** button >> "Click Back to return to the previous screen."

**Comment by strambc** [comment]
"Hardware explorer"  menu title >> "Hardware component selection: Use this menu to select hardware components to include in this Microscope file. Please follow these steps: 1) Open an individual menu. 2) Drag-and-drop the desired element into the main canvas. 3) Click on the desired element to enter the information you want to document. 4) Click on Confirm to save the information you have entered.

**Comment by Akramhar** [comment]
in window 3 we are missing the following tooltips:
-for the dropzone - where you click to load a file after you select 'load a file'
-for the manufactorer selector - where you click to select a manufacturer after you select 'load from repo'
-for the microscope selector - where you click to select a microscope after you select 'load from repo' and a manufacturer

**Comment by strambc** [comment]
Create from file "drop zone" tool-tip >> Select an existing Microscope file you want to work on.
Create from file "drop zone" text >> Select an existing Microscope file you want to work on.
Manufacturer selector >> Select the Manufacturer of the Microscope you want to load.
Microscope selector >> Select the Microscope file you want to load.

**Comment by Akramhar** [comment]
everything in this issue should be included in 0.23

**Comment by strambc** [comment]
Window 1: tooltips missing
Window 2: 
Tier selector >> Tooltip is not correct (see text above).
Continue >> Title: from "Create mode Continue" to "Continue"
