### ISSUE TITLE
Toolbar menu order

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#80]
This is the new order of elements in the menu bar
1 | MicroscopyBasics |  
2a | LightSource |  Transmitted
2b | LightSource |  Fluorescence
3 | LightSourceCoupling |  
4 | Magnification |  
5 | Stage
6 | Focusing
7 | FilterHolder | (currently absent) 
8 | Excitation-Emission |  (currently LightPath)
9 | AdditionalOptics |  
10 | MirroringDevice |  (currently Mirror)
11 | Detector | 
12 | Detector | Detector.PointDetector (currently absent)
13 | Detector | Detector.Camera
14 | Calibration |

**Comment by Akramhar** [comment]
this should be fixed in 0.28
