### ISSUE TITLE
Alternative solution for invalid elements

### ISSUE THREAD

**Issue by Akramhar** [WU-BIMAC/4DNMicroscopyMetadataToolReact#82]
Replace the red border indicator for invalid elements with a green or red indicator placed next to the "grabber"

**Comment by Akramhar** [comment]
should be done in 0.23

**Comment by strambc** [comment]
Tumb up and Tumb down icons are not sufficient HIGH RESOLUTION.
>>> Substitute Red tumb down and Green tumb up with RED and GREEN simple dot

**Comment by Akramhar** [comment]
should be done in 0.26
