### ISSUE TITLE
Tool tips issues

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#86]
Window 2: 
Tier selector >> Tooltip is not correct (see text above).
Continue >> Title: from "Create mode Continue" to "Continue"

**Comment by strambc** [comment]
Related to #76

**Comment by Akramhar** [comment]
Fix the "continue".
The only difference with the "Tier selector" is regarding the link part, that I aligned with the "Validation tier".
Is that the problem you are referring too?

**Comment by strambc** [comment]
ISSUE 1

Tier selector --> tooltip text has a typo.
The correct text of the first sentence should be: "Choose the Tier level you want to document Instrument Hardware Specification and Image Acquisition Setting"
The second sentence is OK as it is.

ISSUE 2
In the Tier validation selector, Tier should be spelled with a capital T

**Comment by Akramhar** [comment]
should be fixed in 0.28
