### ISSUE TITLE
SIZE ISSUE 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#92]
This issue pertains to 
- Microscope Table
- Optovar
- ObjectiveFocusingTurret

**SIDEBAR**
They are too small and cannot be seen.

**WHEN DRAG ON CANVAS**
They do nor resize to correct size

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/85436971-dba49500-b557-11ea-8e8a-051daf4bd17c.png)

**Comment by Akramhar** [comment]
We should talk about how to fix the sidebar, I have no idea atm.
I'm currently unable to reproduce the issue of having "squared" elements as you are showing in the screenshot.

**Comment by strambc** [comment]
THIS ISSUE IS STILL PRESENT.

**Comment by Akramhar** [comment]
it may be solved in 0.28
