### ISSUE TITLE
Icons disappears upon resizing

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#94]
Upon resizing the ICON disappeared.
This happened upon re-opening an existing microscope

[25_microscope_2.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/4821026/25_microscope_2.txt)

**Comment by strambc** [comment]
<img width="232" alt="Additional Optics_Initial size" src="https://user-images.githubusercontent.com/4050585/85437524-b401fc80-b558-11ea-848a-f4816adf6a83.png">
<img width="232" alt="Additional Optics_resize 1" src="https://user-images.githubusercontent.com/4050585/85437525-b49a9300-b558-11ea-8ae9-23c25c430835.png">
<img width="232" alt="Additional Optics_resize 2" src="https://user-images.githubusercontent.com/4050585/85437526-b5332980-b558-11ea-86d5-69a80130fbba.png">
<img width="287" alt="LightSourceCoupling" src="https://user-images.githubusercontent.com/4050585/85437527-b5332980-b558-11ea-9b05-1f0505403ce6.png">

**Comment by strambc** [comment]
At the same time PRISM resized correctly as below
<img width="308" alt="Prism_resize" src="https://user-images.githubusercontent.com/4050585/85437528-b5cbc000-b558-11ea-9e1a-81d1d41ead7e.png">

**Comment by strambc** [comment]
25_Microscope_2 was reloaded and the issue was seen again.

**Comment by strambc** [comment]
When a new empty microscope is created using Create from scratch the behavior does not happen.
When the new microscope was saved (25_Microscope_3) was saved and reopened the same behavior happened again.

[25_microscope_3.txt](https://github.com/WU-BIMAC/4DNMicroscopyMetadataToolReact/files/4821078/25_microscope_3.txt)

**Comment by Akramhar** [comment]
I tried to load the microscope you posted.
It seems to be loading correctly:
![image](https://user-images.githubusercontent.com/3996749/87362517-db872c00-c53c-11ea-8f9a-7f01adb421bb.png)
Could you please tell me more about the issue?
